### ISSUE TITLE
Container stops after steamcmd update

### ISSUE THREAD

**Issue by thawankeane** [Apfelwurm/csgo-get5-docker#20]
When starting a container using the examples in readme, it stops right after update success. (See screenshot below)

![image](https://user-images.githubusercontent.com/26743815/229015293-bbda3e92-390f-4c33-b3b6-0330c7be3651.png)

**Comment by Apfelwurm** [comment]
Hi, thanks for reporting, gonna take a look later. Can you  please provide the exact command line you've used?

**Comment by thawankeane** [comment]
> Hi, thanks for reporting, gonna take a look later. Can you please provide the exact command line you've used?

Excellent, thanks for the reply!

I've used the same commands as in 2.3 topics at README

Such as [this command](https://github.com/Apfelwurm/csgo-get5-docker-dev#231-starting-a-server-with-no-match-config-with-your-local-get5-development-build) and [this one](https://github.com/Apfelwurm/csgo-get5-docker-dev#232-starting-a-server-with-a-match-config)

**Comment by Apfelwurm** [comment]
@thawankeane sorry, missed your comment. I hope i can free some time for the analysis in the next days

**Comment by thawankeane** [comment]
@Apfelwurm I guess that can be related to steamcmd return code at [`server-update.sh`](https://github.com/Apfelwurm/csgo-get5-docker-dev/blob/d4571e4248aff8383f1b81c3e0ffd53e74b83b04/server-scripts/server-update.sh#L1-L5), I've tried to bypass any return code from it using `|| true` at the end of the bash command and looks like it worked.

**Comment by Apfelwurm** [comment]
Firstly, sorry for no reply since over a month.
The problem was that my remote update script overwrites the start CMD line for the container which should be `server-launch.sh` to `server-update.sh`  .
This should be fixed now and should not come up again.
Also the default get5 version that was built into the image is not available anymore, the new default is 0.14.7.
The image is now rebuilt and is pushing (will take a few hours) , so it should work again as expected after another pull in a few hours.

note: you have to use the -it param for the run command, since there seem to be an issue if the container is started non interactive.

I will close this issue, since i found the error. If you have any other problems, let me know :)
